[package]
name = "meta"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["protobuf-codec"]
protobuf-codec = ["raft-proto/protobuf-codec", "bytes"]
prost-codec = ["raft-proto/prost-codec"]

[dependencies]
tokio.workspace = true
tonic.workspace = true
tonic-build.workspace = true

common.workspace = true
thiserror.workspace = true

serde.workspace = true
serde_json.workspace = true

rocksdb.workspace = true
futures.workspace = true

raft-proto.workspace = true
protocol.workspace = true
protobuf.workspace = true
raft.workspace = true
prost.workspace = true

bytes = { version = "1", optional = true, features = ["serde"] }

slog = "2"
slog-term = "2.9.0"
slog-async = "2.8.0"
