[package]
name = "meta"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
tonic.workspace = true
prost.workspace = true
protobuf.workspace = true
common.workspace = true
tonic-build.workspace = true
thiserror.workspace = true
raft.workspace = true
serde.workspace = true
bytes.workspace = true
rocksdb.workspace = true
serde_json.workspace = true
protocol.workspace =true
futures.workspace =true
raft-proto.workspace = true
slog = "2"
slog-term = "2.9.0"
slog-async = "2.8.0"