[package]
name = "robustmq"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.10.0"
log4rs = "1.2.0"
serde = "1.0"
serde_yaml = "0.9"
indoc = "2.0"
serde_derive = "1.0"
toml ="0.8.2"

rlog = { path = "src/rlog", version = "0.1.0" }
config = { path = "src/config", version = "0.1.0" }
metrics = { path = "src/metrics", version = "0.1.0" }