[workspace]
members = [
    "src/admin",
    "src/broker",
    "src/cmd",
    "src/common/config",
    "src/common/log",
    "src/common/metrics",
    "src/common/version",
    "src/common/base",
    "src/meta",
    "src/protocol"
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
serde = {version="1.0",features = [ "derive" ]}
serde_json = "1.0"
signal-hook = "0.3.17"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.9", features = ["codec"] }
axum = "0.6.16"
prometheus = "0.13.3"
prometheus_exporter = "0.8"
lazy_static = "^1.4"
futures = "0.3"
thiserror = "1" #错误定义和处理
bytes = { version = "1", features = ["serde"] }
protobuf = "2.23"
rocksdb = "0.21.0"
tonic = "0.10.2"
prost = "0.12"
prost-types = "0.12"
prost-build = { version = "0.12" }
tonic-build = "0.10.2"
raft = { version = "0.7.0" }
slog = "2.2"
slog-async = "2.3.0"
slog-envlogger = { version = "2.1.0"}
slog-stdlog = { version = "4"}
slog-term = { version = "2.4.0"}

## workspaces members
admin={path="src/admin"}
broker={path="src/broker"}
cmd={path="src/cmd"}
common-base={path="src/common/base"}
common-config={path="src/common/config"}
common-log={path="src/common/log"}
common-metrics={path="src/common/metrics"}
common-version={path="src/common/version"}
meta={path="src/meta"}
protocol={path="src/protocol"}

[profile.release]
panic = 'abort'
debug = true

[profile.nightly]
inherits = "release"
strip = true
lto = "thin"
debug = false
incremental = false