[package]
name = "robustmq"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.10.0"
log4rs = "1.2.0"
serde = {version="1.0",features = [ "derive" ]}
toml = "0.8.2"
signal-hook = "0.3.17"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.9", features = ["codec"] }
axum = "0.6.16"
prometheus = "0.13.3"
prometheus_exporter = "0.8"
lazy_static = "^1.4"
futures = "0.3"
thiserror = "1" #错误定义和处理
bytes = { version = "1", features = ["serde"] }
protobuf = "2.23"
rocksdb = "0.21.0"
clap = {version="4.4.7",features = [ "derive" ]}
serde_json = "1.0"
tonic = "0.10.2"
prost = "0.12"
prost-types = "0.12"
prost-build = { version = "0.12" }
tonic-build = "0.10.2"
raft = { version = "0.7.0" }
ntex = {version = "0.7.4", features = ["tokio"] }
ntex-util = "0.3.2"
ntex-mqtt = "0.12.7"

[[bin]]
name = "robustmq-server"
path = "src/server.rs"

[profile.release]
panic = 'abort'

[[example]]
name = "mqtt_server"
path = "src/broker/mqttserver.rs"