[package]
name = "robustmq"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.10.0"
log4rs = "1.2.0"
serde = "1.0"
toml ="0.8.2"
signal-hook = "0.3.17"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.9", features = ["codec"] }
axum="0.6.16"
prometheus = "0.13.3"
prometheus_exporter = "0.8"
lazy_static = "^1.4"

[[bin]]
name = "robustmq-server"
path = "src/server.rs"

[profile.release]
panic = 'abort'