node_id = 2
addr = "127.0.0.1"
port = 2228
admin_port = 2227
nodes = { 1 = "127.0.0.1:1228", 2 = "127.0.0.1:2228", 3 = "127.0.0.1:3228" }
runtime_work_threads = 100
data_path = "/tmp/robust2/data"
log_path = "/tmp/robust2/logs"
log_segment_size = 1099511627776
log_file_num=50

[rocksdb]
max_open_files = 10000
