[package]
name = "cmd"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "robustmq"

[[broker]]
name = "broker"
path = "src/broker.rs"

[[cmd]]
name = "cmd"
path = "src/cmd.rs"

[[meta]]
name = "meta"
path = "src/meta.rs"

[[bin]]
name = "robustmq"
path = "src/robust.rs"

[dependencies]
clap = {version="4.4.7",features = [ "derive" ]}
common.workspace = true
lazy_static.workspace = true
tokio.workspace = true
broker.workspace = true
meta.workspace = true
