[package]
name = "cmd"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "robustmq"

[[bin]]
name = "mqtt"
path = "src/mqtt/broker.rs"

[[bin]]
name = "cmd"
path = "src/cmd/cmd.rs"

[[bin]]
name = "meta"
path = "src/meta/meta.rs"

[[bin]]
name = "robustmq"
path = "src/robust/robust.rs"

[dependencies]
clap = {version="4.4.7",features = [ "derive" ]}
common.workspace = true
lazy_static.workspace = true
tokio.workspace = true
mqtt-broker.workspace = true
meta-server.workspace = true
