[package]
name = "metadata-struct"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
common-base.workspace = true
serde_json.workspace = true