[package]
name = "common-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
toml = "0.8.2"
common-log.workspace=true
serde.workspace=true
serde_json.workspace=true