port = 9981
placement_center = ["127.0.0.1:1228"]

[mqtt]
mqtt4_enable = true
mqtt5_enable = true
websocket_enable = true
mqtt4_port = 1883
mqtts4_port = 8883
mqtt5_port = 1884
mqtts5_port = 8884
websocket_port = 8083
websockets_port = 8084

[prometheus]
enable = true
port = 8081

[runtime]
worker_threads = 8

[network_tcp]
accept_thread_num = 1
handler_thread_num = 1
response_thread_num = 1
max_connection_num = 1000
request_queue_size = 2000
response_queue_size = 2000
lock_max_try_mut_times = 30
lock_try_mut_sleep_time_ms = 1

[log]
log_path = "/tmp/logs"
log_segment_size = 1073741824
log_file_num = 50
