[inner.service]
port = 9981

[placement.center]
addrs = ["127.0.0.1:1228"]

[mqtt]
mqtt4_enable = true
mqtt5_enable = true
websocket = true
mqtt4_port = 1883
mqtts4_port = 8883
mqtt5_port = 1884
mqtts5_port = 8884
websocket_port = 8083
websockets_port = 8084

[prometheus]
export_port = 8081

[runtime]
data_worker_threads = 8
inner_worker_threads = 8

[tcp_server]
accept_thread_num = 1
handler_thread_num = 20
response_thread_num = 2
max_connection_num = 1000
request_queue_size = 2000
response_queue_size = 2000

[log]
log_path = "/tmp/logs"
log_segment_size = 1073741824
log_file_num = 50
