refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} [{t}] {h({l})} {M}:{m}{n}"
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} [{t}] {h({l})} {M}: {m}{n}"
  foo:
  #限制日志文件大小的配置
    kind: rolling_file
    path: "log/foo.{}.log"
    policy:
      trigger:
        kind: size
        limit: 1024
      roller:
        kind: delete
  bar:
  #限制日志文件数量的配置
    kind: rolling_file
    path: "log/foo.{}.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 200
      roller:
        kind: fixed_window
        pattern: 'log/foo.{}.log'
        base: 0
        count: 5

root:
  level: debug
  appenders:
    - stdout
    - bar
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - requests
    additive: false