refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} [{t}] {h({l})} {M}:{m}{n}"
  server:
    kind: rolling_file
    path: "log/server.log"
    append: true
    encoder:
      pattern: "{d} [{t}] {h({l})} {M}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1024mb
      roller:
        kind: fixed_window
        pattern: 'log/server.{}.log'
        base: 0
        count: 50
  meta:
    kind: rolling_file
    path: "log/meta.log"
    append: true
    encoder:
      pattern: "{d} [{t}] {h({l})} {M}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1024mb
      roller:
        kind: fixed_window
        pattern: 'log/meta.{}.log'
        base: 0
        count: 50
root:
  level: debug
  appenders:
    - stdout
loggers:
  app::server:
    level: info
    appenders:
      - stdout
      - server
    additive: false
  app::meta:
    level: info
    appenders:
      - stdout
      - meta
    additive: false