cluster_name = "mqtt-broker"
broker_id = 1
grpc_port = 9981
http_port = 9982

[storage]
metadata = "memory"
message = "memory"

[mysql]
server = "mysql://root:123456@127.0.0.1:3306/mqtt"

[journal]
server = []

[placement]
server = ["127.0.0.1:1228"]

[mqtt]
tcp_port = 1883
tcps_port = 1884
websocket_port = 8083
websockets_port = 8084
quic_port = 9083
tls_cert = "/Users/bytedance/Desktop/code/robustmq-project/robustmq/config/certs/cert.pem"
tls_key = "/Users/bytedance/Desktop/code/robustmq-project/robustmq/config/certs/key.pem"

[system]
system_user = "admin"
system_password = "pwd123"

[runtime]
worker_threads = 128

[network_tcp]
accept_thread_num = 1
handler_thread_num = 1
response_thread_num = 1
max_connection_num = 1000
request_queue_size = 2000
response_queue_size = 2000
lock_max_try_mut_times = 30
lock_try_mut_sleep_time_ms = 50


[log]
log_path = "/tmp/logs"
log_segment_size = 1073741824
log_file_num = 50
