addr = "127.0.0.1"
grpc_port = 9987
admin_port = 9988

[mqtt]
mqtt4_port = 9989
mqtt5_port = 9990
websocket_port = 9991 

[broker]
port = 1226
work_thread = 3

[runtime]
data_worker_threads = 3
inner_worker_threads = 3

[network]
accept_thread_num = 1
handler_thread_num = 20
response_thread_num = 2
max_connection_num = 1000
request_queue_size = 2000
response_queue_size = 2000

[meta]
port = 1228
dataFold = "/data/robustmq/meta"
