[package]
name = "third-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
common-base.workspace = true
mysql.workspace = true