name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@nextest
    - uses: actions/checkout@v3
    - name: Build
      run: make release
    - name: Run tests
      run: make test
