name: Integration Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/install-action@nextest
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test
